### ISSUE TITLE
[enhancement]明确shmtu_num_pwd.numpwd路径

### ISSUE THREAD

**Issue by colommar** [a645162/Digital-SHMTU-Tools#3]
比较有意思的是，我直接将`template`中的内容直接拉到Digital-SHMTU-Tools-1.0.0文件夹中，但显然这个并不可行，因为main.py中使用的是`config.read(r"..\shmtu_num_pwd.numpwd")`
我认为改成`config.read(r"template\shmtu_num_pwd.numpwd")`，同时增加
```
[User]
id=your_id
pwd=your_pwd
```
能够让使用者更加明确使用方式，同时更新readme中内容使得使用更加方便

**Comment by a645162** [comment]
感谢您的建议，我这两天抽时间修改一下。那段时间修改了忘记写注释了。

**Comment by colommar** [comment]
@a645162 期待您的画饼内哦让那个的实现，这个项目还是挺有意思的，我觉得有一定的意义。

**Comment by a645162** [comment]
这个项目我后面可能不会再继续维护了，我已经在[a645162/SHMTU_CAS](https://github.com/a645162/SHMTU_CAS)中实现了统一认证平台的登录流程以及验证码识别，同时也可以获取到账单，后续可能会制作一个安卓客户端，使用门槛会降低很多。
因此，这个项目我应该是完善使用说明后就不再维护了。

**Comment by colommar** [comment]
> 这个项目我后面可能不会再继续维护了，我已经在[a645162/SHMTU_CAS](https://github.com/a645162/SHMTU_CAS)中实现了统一认证平台的登录流程以及验证码识别，同时也可以获取到账单，后续可能会制作一个安卓客户端，使用门槛会降低很多。 因此，这个项目我应该是完善使用说明后就不再维护了。

好的，有点遗憾，我个人不是很擅长python，不然我感觉我可以尝试完善下功能 : )

**Comment by colommar** [comment]
closed as solved in #4

**Comment by a645162** [comment]
感谢您的帮助，我明天完善这个文档。其实这个项目并不需要完善，使用Selenium本来就是一大遗憾，我已经使用Kotlin+OkHttp完成了登录+获取账单，相当于重写这个项目，这个项目可以制作成一个更傻瓜式的GUI而不是让用户使用Python，Python使用门槛还是比较高的。账单分析这些功能可以在安卓中很简单的实现，而且验证码识别功能的加入可以让用户只需要输入账号密码，后台就自动登录，这样可以自动获取最新消费记录，然后推送到手机通知栏，我觉得这样更加方便，唯一的缺点就是我不会iOS开发，也没有Apple开发者账号，更无法发布到应用商店，因此，苹果用户无法使用。

**Comment by colommar** [comment]
> 这个项目可以制作成一个更傻瓜式的GUI而不是让用户使用Python，Python使用门槛还是比较高的。
* 我认为如果只是使用python实现其中操作并没有过高的门槛，当然如果能做成一个傻瓜式的GUI，我认为更好。
>账单分析这些功能可以在安卓中很简单的实现，而且验证码识别功能的加入可以让用户只需要输入账号密码，后台就自动登录，这样可以自动获取最新消费记录，然后推送到手机通知栏，我觉得这样更加方便
* 我认为`做个图表`，`列出类似年度报告`之类的东西，还是比较有趣的，也确实比较方便。如果是账单分析这种的话，我个人会倾向于使用datafusion，能够快速的进行数据分析与整合。
> 唯一的缺点就是我不会iOS开发，也没有Apple开发者账号，更无法发布到应用商店，因此，苹果用户无法使用。
* 我两者都不会，但是我认为使用flutter也许是一种思路？我自己便是苹果用户，我认为苹果用户倒不一定使用应用商店的应用，签署证书即可。

**Comment by a645162** [comment]
@colommar 感谢你的建议。

> * 我认为如果只是使用python实现其中操作并没有过高的门槛，当然如果能做成一个傻瓜式的GUI，我认为更好。

但是你可能没有考虑过Selenium需要WebDriver配合浏览器版本，以及没有上网工具，可能通过Selenium4自带的这个自动匹配工具下载的十分缓慢。

> * 我认为`做个图表`，`列出类似年度报告`之类的东西，还是比较有趣的，也确实比较方便。如果是账单分析这种的话，我个人会倾向于使用datafusion，能够快速的进行数据分析与整合。

供用户选择自然是好事儿，我这个Py脚本只是导出全部账单到csv，还没有写增量更新。

> * 我两者都不会，但是我认为使用flutter也许是一种思路？我自己便是苹果用户，我认为苹果用户倒不一定使用应用商店的应用，签署证书即可。

并不可以，识别验证码，我需要调用NDK，使用Java JNI本地能力，深度学习模型推理框架是C++的，我的图像处理以及推理代码也都是C++，我那个[SHMTU_CAS](https://github.com/a645162/SHMTU_CAS)，这个东西虽然在各平台实现，但是核心代码都是`CAS_OCR.cpp`这个C++代码，我不太清楚Flutter是如何处理这种事情的，移动技术我不想学习更多了，只能说我尝试去制作一个Android了。

本身我也有MacBook，我也尝试过写iOS，后来放弃学习了~
或许以后我能重构一下Python代码供iOS用户使用吧！比如核心的分析代码用C语言设计？这样可以让Android与Python有相同的算法，可以复用代码。

**Comment by colommar** [comment]
好的，了解了，非常感谢～

---- 回复的原邮件 ----
| 发件人 | Kong ***@***.***> |
| 发送日期 | 2024年03月17日 10:45 |
| 收件人 | a645162/Digital-SHMTU-Tools ***@***.***> |
| 抄送人 | colommar ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [a645162/Digital-SHMTU-Tools] [enhancement]明确shmtu_num_pwd.numpwd路径 (Issue #3) |

@colommar 感谢你的建议。

我认为如果只是使用python实现其中操作并没有过高的门槛，当然如果能做成一个傻瓜式的GUI，我认为更好。

但是你可能没有考虑过Selenium需要WebDriver配合浏览器版本，以及没有上网工具，可能通过Selenium4自带的这个自动匹配工具下载的十分缓慢。

我认为做个图表，列出类似年度报告之类的东西，还是比较有趣的，也确实比较方便。如果是账单分析这种的话，我个人会倾向于使用datafusion，能够快速的进行数据分析与整合。

供用户选择自然是好事儿，我这个Py脚本只是导出全部账单到csv，还没有写增量更新。

我两者都不会，但是我认为使用flutter也许是一种思路？我自己便是苹果用户，我认为苹果用户倒不一定使用应用商店的应用，签署证书即可。

并不可以，识别验证码，我需要调用NDK，使用Java JNI本地能力，深度学习模型推理框架是C++的，我的图像处理以及推理代码也都是C++，我那个SHMTU_CAS，这个东西虽然在各平台实现，但是核心代码都是CAS_OCR.cpp这个C++代码，我不太清楚Flutter是如何处理这种事情的，移动技术我不想学习更多了，只能说我尝试去制作一个Android了。

本身我也有MacBook，我也尝试过写iOS，后来放弃学习了~
或许以后我能重构一下Python代码供iOS用户使用吧！比如核心的分析代码用C语言设计？这样可以让Android与Python有相同的算法，可以复用代码。
